### ISSUE TITLE
Add N/2, N/3 greatest Number In CPP

### ISSUE THREAD

**Issue by iaryangoyal** [iaryangoyal/DSA-Code-Snippet#4]

**Comment by AlcatrazFP** [comment]
can you give more detail about the problem

**Comment by iaryangoyal** [comment]
@Aniket-Srivastava-21 if you have same sol then no problem create pr it you can optimize then go for it

**Comment by Aniket-Srivastava-21** [comment]
@iaryangoyal I have created PR #21.
