### ISSUE TITLE
Add Merge overlapping intervals Algo in Cpp

### ISSUE THREAD

**Issue by iaryangoyal** [iaryangoyal/DSA-Code-Snippet#5]

**Comment by sgaurav37533** [comment]
hey can you assign me this issue @iaryangoyal

**Comment by iaryangoyal** [comment]
Yeah Sure @sgaurav37533

**Comment by yoqwerty** [comment]
Hi @iaryangoyal can I contribute for this algo and few others mentioned in the issues in Python?

**Comment by iaryangoyal** [comment]
You can do in any language You wish just make new folder if there required for new language
