### ISSUE TITLE
Add Buy / Sell stocks - I, II, III Aglo in Cpp

### ISSUE THREAD

**Issue by iaryangoyal** [iaryangoyal/DSA-Code-Snippet#7]
https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

**Comment by Hariprasad19036** [comment]
Can I work on this issue under the hacktoberfest label?

**Comment by iaryangoyal** [comment]
yes you can @Hariprasad19036

**Comment by sumitmohite0501** [comment]
Please assign this to me , I can solve in cpp
